### ISSUE TITLE
US as 1 country or multiple states

### ISSUE THREAD

**Issue by JindrichSoukup** [JindrichSoukup/covid19#3]
US are huge and temperature in different states differ a lot. Also reaction of each state is different in time. Taking US as 50 states would increase our dataset.
Where to find daily cases?

**Comment by justeiva** [comment]
Done - its here https://github.com/CSSEGISandData/COVID-19. 
I have prepared data to have the same format, code for it is this usa_data_prep_script.R

**Comment by JindrichSoukup** [comment]
School closure date for individual US states could be found at https://www.edweek.org/ew/section/multimedia/map-coronavirus-and-school-closures.html . Details available after clicking to a state

**Comment by justeiva** [comment]
I have also added usa population data together with world population data, so we will be able to filter based on size, there are some states less thant 1mln. I will gather usa states school dates from the link you have provided.

**Comment by JindrichSoukup** [comment]
Thanks, I'll focus on temperature data.

**Comment by justeiva** [comment]
I have downloaded usa schools closure dates per state - schools_closing_usa.csv.

**Comment by justeiva** [comment]
There are many changes going on new john hopkins uni repo, so for now i cant pull from there newest cases of usa data anymore until they finalize it.  They are also planning to add number  of tests - which can be useful for us too. 
For usa cases data i took this alternative for now  https://github.com/nytimes/covid-19-data
